### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by pandastic**
Hello, love that you've chosen Kotlin!  
This fixes a typo with the `blockSignature` property

### CODE REVIEW

**Review by Guppster — APPROVED** [review]
Haha I always spell 'signature' incorrectly

**Comment by Guppster** [comment]
Thanks @pandastic

**Comment by pandastic** [comment]
Thanks @Guppster! I'm new to ark what you guys are doing is pretty cool, but I'm not sure the best way to participate in your github dev bounty program. Can I just leave my public address here or is there another way I to ensure my eligibility?

**Comment by Guppster** [comment]
Don't worry about having to track your contributions. You don't need to expose your address here. As long as you submit PRs to any of the repositories in the bounty program, you will get acknowledged. As far as i am aware @boldninja handles all of that stuff. Feel free to join the Ark slack (https://ark.io/slack) and you can get more info there.

**Comment by boldninja** [comment]
@pandastic provide me with your ARK address or contact me on Ark slack (boldninja) if you don't want to share it publicly.

**Comment by pandastic** [comment]
@boldninja  =(A82

**Pull request merged**
